-- =========================================
-- HOSPITAL MANAGEMENT SYSTEM
-- DOCTOR ANALYTICS
-- Author: Aniket More
-- =========================================

USE hospital_project;

#Total Doctors
SELECT COUNT(*) AS total_doctors
FROM doctors;

#Doctors by Specialization
SELECT
    specialization,
    COUNT(*) AS total_doctors
FROM doctors
GROUP BY specialization
ORDER BY total_doctors DESC;

#Most Experienced Doctors
SELECT
    doctor_id,
    first_name,
    last_name,
    specialization,
    years_experience
FROM doctors
ORDER BY years_experience DESC;

#Appointments Handled by Each Doctor
SELECT
    d.doctor_id,
    d.first_name,
    d.last_name,
    COUNT(a.appointment_id) AS total_appointments
FROM doctors d
JOIN appointment a
ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id,
         d.first_name,
         d.last_name
ORDER BY total_appointments DESC;

#Top 5 Doctors by Appointments
SELECT
    d.doctor_id,
    d.first_name,
    d.last_name,
    COUNT(a.appointment_id) AS total_appointments
FROM doctors d
JOIN appointment a
ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id,
         d.first_name,
         d.last_name
ORDER BY total_appointments DESC
LIMIT 5;

#Doctor Performance by Appointment Status
SELECT
    d.first_name,
    d.last_name,
    a.status,
    COUNT(*) AS total
FROM doctors d
JOIN appointment a
ON d.doctor_id = a.doctor_id
GROUP BY d.first_name,
         d.last_name,
         a.status
ORDER BY d.first_name;

#Revenue Generated by Doctor
SELECT
    d.first_name,
    d.last_name,
    SUM(b.amount) AS revenue_generated
FROM doctors d
JOIN appointment a
    ON d.doctor_id = a.doctor_id
JOIN treatments t
    ON a.appointment_id = t.appointment_id
JOIN billing b
    ON t.treatment_id = b.treatment_id
GROUP BY d.first_name,
         d.last_name
ORDER BY revenue_generated DESC;

#Top Revenue Generating Doctor
SELECT
    d.first_name,
    d.last_name,
    SUM(b.amount) AS revenue_generated
FROM doctors d
JOIN appointment a
    ON d.doctor_id = a.doctor_id
JOIN treatments t
    ON a.appointment_id = t.appointment_id
JOIN billing b
    ON t.treatment_id = b.treatment_id
GROUP BY d.first_name,
         d.last_name
ORDER BY revenue_generated DESC
LIMIT 1;