-- =========================================
-- HOSPITAL MANAGEMENT SYSTEM
-- PATIENT ANALYTICS
-- Author: Aniket More
-- =========================================

USE hospital_project;

#Total Patients
SELECT COUNT(*) AS total_patients
FROM patients;

#Gender Distribution
SELECT
    gender,
    COUNT(*) AS total_patients
FROM patients
GROUP BY gender;

#Patients Registered by Insurance Provider
SELECT
    insurance_provider,
    COUNT(*) AS total_patients
FROM patients
GROUP BY insurance_provider
ORDER BY total_patients DESC;

#Most Frequent Patients
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    COUNT(a.appointment_id) AS total_visits
FROM patients p
JOIN appointment a
ON p.patient_id = a.patient_id
GROUP BY p.patient_id,
         p.first_name,
         p.last_name
ORDER BY total_visits DESC;

#Top 5 Most Frequent Patients
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    COUNT(a.appointment_id) AS total_visits
FROM patients p
JOIN appointment a
ON p.patient_id = a.patient_id
GROUP BY p.patient_id,
         p.first_name,
         p.last_name
ORDER BY total_visits DESC
LIMIT 5;

#Revenue Generated by Each Patient
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    SUM(b.amount) AS total_spent
FROM patients p
JOIN billing b
ON p.patient_id = b.patient_id
GROUP BY p.patient_id,
         p.first_name,
         p.last_name
ORDER BY total_spent DESC;

#Top 5 Highest Spending Patients
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    SUM(b.amount) AS total_spent
FROM patients p
JOIN billing b
ON p.patient_id = b.patient_id
GROUP BY p.patient_id,
         p.first_name,
         p.last_name
ORDER BY total_spent DESC
LIMIT 5;

#Average Spending per Patient
SELECT
    AVG(amount) AS average_patient_spending
FROM billing;

#Patients with Pending Bills
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    b.amount
FROM patients p
JOIN billing b
ON p.patient_id = b.patient_id
WHERE b.payment_status = 'Pending';