-- =========================================
-- HOSPITAL MANAGEMENT SYSTEM
-- JOINS ANALYSIS
-- Author: Aniket More
-- =========================================

USE hospital_project;

#Patient Appointment Details
SELECT
    p.patient_id,
    p.first_name,
    p.last_name,
    a.appointment_date,
    a.reason_for_visit,
    a.status
FROM patients p
JOIN appointment a
ON p.patient_id = a.patient_id;

#Patient + Doctor Details
SELECT
    p.first_name AS patient_first_name,
    p.last_name AS patient_last_name,
    d.first_name AS doctor_first_name,
    d.last_name AS doctor_last_name,
    d.specialization,
    a.appointment_date
FROM appointment a
JOIN patients p
ON a.patient_id = p.patient_id
JOIN doctors d
ON a.doctor_id = d.doctor_id;

#Appointment + Treatment Details
SELECT
    a.appointment_id,
    a.appointment_date,
    t.treatment_type,
    t.cost
FROM appointment a
JOIN treatments t
ON a.appointment_id = t.appointment_id;

#Treatment + Billing Details
SELECT
    t.treatment_type,
    t.cost,
    b.amount,
    b.payment_status
FROM treatments t
JOIN billing b
ON t.treatment_id = b.treatment_id;

#Complete Patient Journey
SELECT
    p.patient_id,
    CONCAT(p.first_name,' ',p.last_name) AS patient_name,
    CONCAT(d.first_name,' ',d.last_name) AS doctor_name,
    d.specialization,
    a.appointment_date,
    t.treatment_type,
    b.amount,
    b.payment_status
FROM patients p
JOIN appointment a
ON p.patient_id = a.patient_id
JOIN doctors d
ON a.doctor_id = d.doctor_id
JOIN treatments t
ON a.appointment_id = t.appointment_id
JOIN billing b
ON t.treatment_id = b.treatment_id;

#Revenue Generated by Each Doctor
SELECT
    CONCAT(d.first_name,' ',d.last_name) AS doctor_name,
    SUM(b.amount) AS total_revenue
FROM doctors d
JOIN appointment a
ON d.doctor_id = a.doctor_id
JOIN treatments t
ON a.appointment_id = t.appointment_id
JOIN billing b
ON t.treatment_id = b.treatment_id
GROUP BY doctor_name
ORDER BY total_revenue DESC;

#Revenue Generated by Each Patient
SELECT
    CONCAT(p.first_name,' ',p.last_name) AS patient_name,
    SUM(b.amount) AS total_spent
FROM patients p
JOIN billing b
ON p.patient_id = b.patient_id
GROUP BY patient_name
ORDER BY total_spent DESC;

#Highest Revenue Appointment
SELECT
    a.appointment_id,
    p.first_name,
    p.last_name,
    b.amount
FROM appointment a
JOIN patients p
ON a.patient_id = p.patient_id
JOIN treatments t
ON a.appointment_id = t.appointment_id
JOIN billing b
ON t.treatment_id = b.treatment_id
ORDER BY b.amount DESC
LIMIT 1;

#Doctor-wise Treatment Count
SELECT
    CONCAT(p.first_name,' ',p.last_name) AS patient_name,
    b.amount,
    b.payment_status
FROM patients p
JOIN billing b
ON p.patient_id = b.patient_id
WHERE b.payment_status = 'Pending';